version: '2.1'
services:
    postgres:
        container_name: "postgres"
        image: postgres:9.6
        volumes:
            - ${HOME}/postgres_mount/postgres:/var/lib/postgresql/data        
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        container_name: "webserver"
        image: my-airflow-presentation-webserver:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - EXECUTOR=Local
        volumes:
            - ${HOME}/airflow_mount/dags:/usr/local/airflow/dags
            - ${HOME}/airflow_mount/logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        container_name: "scheduler"
        image: my-airflow-presentation-scheduler:latest
        restart: always
        depends_on:
            - webserver
        environment:
            - EXECUTOR=Local
        volumes:
            - ${HOME}/airflow_mount/dags:/usr/local/airflow/dags
            - ${HOME}/airflow_mount/logs:/usr/local/airflow/logs


    data_postgres:
        container_name: "data_postgres"
        image: my-airflow-data-postgres:latest
        volumes:
            - ${HOME}/postgres_mount_data/postgres:/var/lib/postgresql/data        
        environment:
            - POSTGRES_USER=promotions
            - POSTGRES_PASSWORD=promotions
            - POSTGRES_DB=promotions                        
            
    data_server:
        container_name : "data_server"
        image: my-airflow-presentation-dataserver:latest
        depends_on:
            - data_postgres
        ports:
            - "9000:9000"

            